import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const origin = (process.env.SITE_ORIGIN || 'https://toraikura.github.io/chill-labo-next').replace(/\/$/, '');
const indexable = process.env.SITE_INDEXABLE === 'true';
if (!/^https:\/\//.test(origin)) throw new Error('SITE_ORIGIN must be an HTTPS URL');
if (indexable && new URL(origin).hostname.endsWith('github.io')) throw new Error('Keep the preview noindex until the official-domain launch');
const links = {
  reserve: 'https://www.instagram.com/CHILLLABOTOKYO/',
  maps: 'https://maps.app.goo.gl/GPKRcTt7F3grPJck7',
  course: 'https://www.tablecheck.com/ja/chilllabo-tokyo',
  sat: 'https://sakearttokyo.com/',
  play: 'https://toraikura.github.io/sat-fermentation-playground/',
};
const esc = s => String(s).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const hotels = [
  ['アパホテル〈赤坂見附〉', 'APA Hotel Akasaka Mitsuke', '3-19-10'],
  ['OMO3東京赤坂 by 星野リゾート', 'OMO3 Tokyo Akasaka by Hoshino Resorts', '4-3-2'],
  ['スーパーホテルPremier赤坂', 'SUPER HOTEL Premier Akasaka', '3-16-7'],
  ['センチュリオンホテル レジデンシャル赤坂', 'Centurion Hotel Residential Akasaka', '3-12-3'],
  ['センチュリオンホテル グランド赤坂', 'Centurion Hotel Grand Akasaka', '3-19-3'],
  ['ザ・センチュリオン クラシック赤坂', 'The Centurion Classic Akasaka', '3-11-8'],
  ['the b 赤坂見附', 'the b akasaka-mitsuke', '3-21-7'],
  ['ホテルヒラリーズ赤坂', 'Hotel Hillarys Akasaka', '3-12-5'],
];

function render(lang) {
  const en = lang === 'en';
  const t = (ja, english) => en ? english : ja;
  const base = en ? '../' : './';
  const canonical = `${origin}/${en ? 'en/' : ''}`;
  const title = t('赤坂の日本酒バー・飲み比べ｜Chill Labo Akasaka – Japanese Sake Bar', 'Japanese Sake Bar in Akasaka, Tokyo | Chill Labo');
  const description = t('赤坂の日本酒バー、Chill Labo Akasaka。100種類以上を飲み比べ。最初の1時間3,300円（税込）、自動延長1時間1,100円。料理付きコース、営業時間、予約、駅からの道順をご案内。', 'Explore 100+ sake selections in Akasaka, Tokyo. English support available. First hour ¥3,300 incl. tax. See tasting prices, food courses and directions.');
  const ext = (href, label, cls = 'text-link', event = '') => `<a href="${esc(href)}" class="${cls}" target="_blank" rel="noopener noreferrer"${event ? ` data-track="${event}"` : ''}>${label}<span aria-hidden="true">↗</span></a>`;
  const reserve = () => ext(links.reserve, t('Instagramで予約', 'Reserve via Instagram'), 'button button-red reservation-link', 'reservation_outbound');
  const maps = (short = false) => ext(links.maps, short ? t('地図', 'Maps') : 'Google Maps', 'button button-outline', 'maps_outbound');
  const actions = () => `<div class="actions inline-actions">${reserve()}${maps(true)}</div>`;
  const photo = (name, large, width, height, alt, cls = '', eager = false) => `<img class="${cls}" src="${base}assets/images/${name}-${large}.webp" srcset="${base}assets/images/${name}-480.webp 480w, ${base}assets/images/${name}-${large}.webp ${large}w" sizes="${eager ? '(max-width: 600px) 450px, 600px' : '(max-width: 700px) 100vw, 50vw'}" width="${width}" height="${height}" alt="${esc(alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  const faqs = [
    [t('日本酒に詳しくなくても大丈夫？', 'Do I need to know about sake?'), t('もちろんです。普段好きな飲みものや味から、一緒に探しましょう。初心者の方、お一人様も歓迎しています。', 'Not at all. Tell us about the drinks and flavors you enjoy, and we can help you explore. Beginners and solo guests are welcome.')],
    [t('飲み比べの料金は？', 'How much does sake tasting cost?'), t('最初の1時間はお一人様3,300円（税込）。その後は1時間ごとに1,100円（税込）で自動延長です。通常の飲み比べ料金に料理は含まれません。', 'The first hour is ¥3,300 per person, tax included. Extensions are automatic at ¥1,100 per additional hour. Food is ordered separately.')],
    [t('席料はかかりますか？', 'Is there a table charge?'), t('飲み比べ放題には席料がかかりません。単品注文のみの場合は、お一人様550円（税込）の席料を頂戴します。', 'There is no table charge with the tasting plan. For à la carte orders only, a table charge of ¥550 per person applies, including tax.')],
    [t('英語でも相談できますか？', 'Is English support available?'), t('英語対応スタッフがおり、一部メニューにも英語表記があります。気軽にお声がけください。', 'English-speaking staff are available, and some menu information is in English. Please feel free to ask for help.')],
    [t('予約なしでも入れますか？', 'Can I walk in without a reservation?'), t('お席があればご案内できます。金曜日の3名様以上は、ご予約をおすすめします。16時以降の当日予約はお電話でお問い合わせください。', 'Walk-ins are welcome when seats are available. We recommend booking for Friday groups of three or more. For same-day reservations after 16:00 JST, please call.')],
    [t('料理付きコースはありますか？', 'Do you offer tasting courses with food?'), t('2時間6,600円、3時間8,800円（各お一人様・税込）の料理付きコースがあります。2〜10名様、月〜金、2日前までのご予約制です。10名様はお電話でお問い合わせください。', 'Yes: a 2-hour course at ¥6,600 or a 3-hour course at ¥8,800 per person, tax included. Available for 2–10 guests, Monday–Friday, with booking at least 2 days ahead. For 10 guests, please call.')],
    [t('日本酒以外の飲みものは？', 'Are other drinks available?'), t('飲み比べ放題には、焼酎・ビール・ソフトドリンクも含まれます。日本酒は冷酒・常温・熱燗を楽しめます。', 'Shochu, beer and soft drinks are also included in the tasting plan. Sake is available chilled, at room temperature and warm.')],
    [t('食べものの持ち込みはできますか？', 'Can I bring my own food?'), t('フードの持ち込みはご遠慮いただいています。店内のおつまみをお楽しみください。おでんは月〜金に提供しています。', 'Please do not bring outside food. We serve appetizers at the bar, with oden available Monday–Friday.')],
    [t('駅からどのくらいですか？', 'How do I get there?'), t('赤坂駅・赤坂見附駅から、それぞれ徒歩約5分。東京都港区赤坂4-3-27の2Fです。路地の写真とGoogle Mapsをご確認ください。', 'We are about a 5-minute walk from either Akasaka Station or Akasaka-mitsuke Station. The bar is on 2F at 4-3-27 Akasaka, Minato-ku, Tokyo. See the alley photo and Google Maps for directions.')],
    [t('支払い方法は？', 'How can I pay?'), t('現金・クレジットカード・PayPayをご利用いただけます。', 'We accept cash, credit cards and PayPay.')],
    [t('店内で喫煙できますか？', 'Is smoking allowed?'), t('店内は禁煙です。屋外に喫煙スペースがあります。', 'The bar is non-smoking indoors. A smoking area is available outside.')],
    [t('1Fでボトルは買えますか？', 'Can I buy a bottle on 1F?'), t('1FのBottle Shopは準備中です。営業開始や販売内容は、決まり次第ご案内します。', 'Our 1F Bottle Shop is in preparation. Opening and sales details will be announced when confirmed.')],
  ];
  const schema = {
    '@context': 'https://schema.org', '@type': 'BarOrPub', '@id': 'https://chilllabo.tokyo/#chill-labo-akasaka',
    name: 'Chill Labo Akasaka', alternateName: 'チルラボ', description,
    url: canonical, image: `${origin}/assets/images/01-pouring-900.webp`, telephone: '+81-80-8700-8528',
    address: { '@type': 'PostalAddress', streetAddress: '4-3-27 Akasaka, 2F', addressLocality: 'Minato-ku', addressRegion: 'Tokyo', postalCode: '107-0052', addressCountry: 'JP' },
    openingHoursSpecification: [
      { '@type': 'OpeningHoursSpecification', dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], opens: '17:00', closes: '23:00' },
      { '@type': 'OpeningHoursSpecification', dayOfWeek: 'Saturday', opens: '15:00', closes: '22:00' },
    ],
    servesCuisine: ['Japanese', 'Sake'], currenciesAccepted: 'JPY', paymentAccepted: 'Cash, Credit Card, PayPay',
    hasMap: links.maps, sameAs: [links.reserve], acceptsReservations: true,
  };
  const course = (hours, price) => `<article class="course">
    <div class="course-heading"><h3><span class="course-number">${hours}<span>${t('時間', 'H')}</span></span><span>${t('飲み比べコース', 'Sake tasting course')}</span></h3><p class="course-price">¥${price}<small>${t('1名様・税込', 'per person · tax included')}</small></p></div>
    <p class="course-terms">${t('2〜10名様 · 月〜金 · 2日前までに予約', '2–10 guests · Mon–Fri · Book at least 2 days ahead')}</p>
    <details><summary>${t('料理の内容を見る', 'View the food menu')}<span class="toggle" aria-hidden="true"></span></summary><div class="details-content"><ul class="food-list">
      <li>${t('小鉢おまかせ盛り！おつまみプレート', 'Chef’s selection of small appetizers')}</li>
      <li>${t('ベーコンと玉ねぎのポテトサラダ', 'Potato salad with bacon and onion')}</li>
      <li>${t('炙り合鴨ロース', 'Seared duck loin')}</li>
      ${hours === 3 ? `<li>${t('元おでん屋がつくる！おでん盛り合わせ', 'Assorted oden')}</li><li>${t('〆のパスタ', 'Pasta to finish')}</li>` : ''}
    </ul>${hours === 2 ? `<p class="fine">${t('追加フードはコース終了30分前まで。おでん・〆は提供にお時間を頂くため、45分前までにご注文ください。お時間終了後は、次のお客様のため速やかなご退店をお願いいたします。', 'Additional food orders close 30 minutes before your course ends. Please order any additional oden or finishing dishes at least 45 minutes before the end, as they take longer to prepare. Please leave promptly at the end of your course so we can welcome the next guests.')}</p>` : ''}</div></details>
  </article>`;
  const dm = t('チルラボ赤坂の予約をお願いします。日付：［月／日］、時間：［時：分］、人数：［名］。よろしくお願いします。', 'Hello! I’d like to reserve a table at Chill Labo Akasaka. Date: [date]. Time: [time, JST]. Guests: [number]. Thank you!');
  const nav = `<a href="#pricing">${t('飲み比べ・料金', 'Tasting & prices')}</a><a href="#house">1F ${t('ボトルショップ', 'Bottle Shop')}</a><a href="#access">${t('アクセス', 'Visit')}</a>`;
  return `<!doctype html>
<html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${indexable ? 'index,follow' : 'noindex,follow'}">
<link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="ja" href="${origin}/"><link rel="alternate" hreflang="en" href="${origin}/en/"><link rel="alternate" hreflang="x-default" href="${origin}/">
<meta property="og:type" content="website"><meta property="og:site_name" content="Chill Labo Akasaka"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:locale" content="${en ? 'en_US' : 'ja_JP'}"><meta property="og:locale:alternate" content="${en ? 'ja_JP' : 'en_US'}"><meta property="og:image" content="${origin}/assets/images/01-pouring-900.webp"><meta property="og:image:width" content="900"><meta property="og:image:height" content="900"><meta property="og:image:alt" content="${t('グラスに注がれる日本酒', 'Sake being poured into a glass')}"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#f7f0dc">
<link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/fonts/Anton-Regular-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${base}assets/css/styles.css?v=20260911"><script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script><script src="${base}assets/js/site.js?v=20260911" defer></script>
</head><body id="top">
<a href="#main" class="skip-link">${t('本文へスキップ', 'Skip to main content')}</a>
<header class="site-header"><a class="brand" href="#top" aria-label="Chill Labo Akasaka — ${t('ページ先頭へ', 'back to top')}"><span class="wordmark">CHILL LABO</span><span class="brand-place">AKASAKA</span></a><nav class="desktop-nav" aria-label="${t('メインナビゲーション', 'Main navigation')}">${nav}</nav><div class="header-tools"><a class="language-link" href="${en ? '../' : './en/'}" lang="${en ? 'ja' : 'en'}" hreflang="${en ? 'ja' : 'en'}" aria-label="${t('Switch to English', '日本語へ切り替え')}">${t('EN', '日本語')}</a><div class="header-reserve">${reserve()}</div><details class="mobile-menu"><summary aria-label="${t('メニュー', 'Menu')}"><span class="menu-icon" aria-hidden="true"></span></summary><nav aria-label="${t('モバイルナビゲーション', 'Mobile navigation')}">${nav}<a href="#discover">${t('酒づくりと、発見', 'Our sake & discoveries')}</a>${reserve()}</nav></details></div></header>
<main id="main">
<section class="hero" id="enter" aria-labelledby="hero-title">${photo('01-pouring', 900, 900, 900, t('チルラボでグラスに日本酒を注ぐ手元', 'Sake being poured into a glass at Chill Labo'), 'hero-photo', true)}<div class="hero-wash"></div><div class="hero-copy"><h1 id="hero-title" class="eyebrow">${t('赤坂の日本酒バー・飲み比べ / 2F', 'Sake tasting in Akasaka, Tokyo / 2F')}</h1><p class="hero-headline">${t('ひと口ずつ、<br>好きになる。', 'One sip at a time.<br>Find your favorite.')}</p><p class="hero-lead">${t('知らない銘柄も、好きな味から。', 'You don’t need to know the labels.<br>Start with the flavors you like.')}</p></div></section>
<section class="service-strip" aria-label="${t('料金と予約', 'Prices and booking')}"><div class="service-inner"><p class="selection">${t('日本酒', '')}<strong>100</strong>${t('種類以上を飲み比べ', '+ sake selections')}</p><div class="quick-price"><p>${t('最初の1時間', 'First hour')} <strong>¥3,300</strong> <small>${t('税込', 'incl. tax')}</small></p><p class="fine">${t('お一人様 / 自動延長 1時間ごと ¥1,100', 'Per person / Auto-extension ¥1,100 per hour')}</p></div>${actions()}</div></section>
<section class="experience section wrap" id="experience" aria-labelledby="experience-title"><div class="experience-image"><span class="floor-mark">2F</span>${photo('05-selecting-sake', 900, 900, 900, t('冷蔵庫から気になる日本酒を選ぶ', 'Choosing a bottle of sake from the fridge'))}</div><div class="experience-copy"><p class="eyebrow">TASTE / COMPARE / ASK</p><h2 id="experience-title">${t('まずは、ひと口。', 'Start with a sip.')}</h2><p class="intro">${t('飲んで、話して、少しずつ比べる。', 'Taste, talk, and find your next favorite.')}</p><p>${t('好きな味を聞かせてください。気になった一本を少しずつ。知らない銘柄も、ここでは会話のきっかけです。', 'Tell us what you enjoy. Try a little, compare, and ask about the next glass. An unfamiliar sake might become a new favorite.')}</p><p class="welcome">${t('初心者・お一人様歓迎 / English welcome', 'Beginners & solo guests welcome<br>English support available')}</p></div></section>
<section class="pricing section wrap" id="pricing" aria-labelledby="pricing-title"><span id="prices" class="anchor-alias"></span><div class="section-intro"><p class="eyebrow">TAKE YOUR TIME</p><h2 id="pricing-title">${t('飲み比べ放題の料金', 'Sake tasting prices')}</h2><p>${t('好きな味を、好きなペースで。', 'Enjoy our all-you-can-taste plan at your own pace.')}</p></div><div class="price-detail"><dl class="price-table"><div><dt>${t('最初の1時間', 'First hour')}</dt><dd>¥3,300</dd></div><div><dt>${t('自動延長・1時間ごと', 'Each additional hour')}<small>${t('', 'Automatic extension')}</small></dt><dd>¥1,100</dd></div></dl><p class="fine">${t('お一人様・税込。時間経過により自動延長となります。', 'Per person, in Japanese yen, tax included. Extensions are automatic.')}</p><p>${t('冷酒・常温・熱燗。焼酎・ビール・ソフトドリンクも含みます。', 'Chilled, room-temperature and warm sake. Shochu, beer and soft drinks are also included.')}</p><p class="fine">${t('飲み比べ放題は席料なし。単品注文のみの場合は席料お一人様550円（税込）。料理は別注文です。', 'No table charge with the tasting plan. For à la carte orders only, a ¥550 table charge applies per person, including tax. Food is ordered separately.')}</p><div class="inline-actions">${reserve()}</div></div></section>
<section class="food section wrap" id="food" aria-labelledby="food-title"><div class="food-copy"><p class="eyebrow">A BITE WITH YOUR SAKE</p><h2 id="food-title">${t('一杯のとなりに、<br>ひと皿。', 'A little something<br>alongside.')}</h2><p>${t('湯気の向こうで、またひと口。<br>おつまみをつまみながら、ゆっくりどうぞ。', 'Settle in with a plate of appetizers<br>and a glass of sake.')}</p><p class="fine">${t('おでんは月〜金に提供しています。<br>フードのお持ち込みはご遠慮ください。', 'Oden is served Monday–Friday.<br>Please do not bring outside food.')}</p></div><figure>${photo('02-oden', 900, 900, 900, t('湯気が上がるチルラボのおでん', 'Oden simmering at Chill Labo'))}<figcaption>ODEN / CHILL LABO</figcaption></figure></section>
<section class="courses section wrap" id="courses" aria-labelledby="courses-title"><div class="section-intro"><p class="eyebrow">SAKE & FOOD</p><h2 id="courses-title">${t('料理付き<br>飲み比べコース', 'Sake tasting<br>with food')}</h2><p>${t('料理も楽しみたい日は、こちらを。', 'Bring a friend, share the food, and explore sake together.')}</p></div><div class="course-list">${course(2, '6,600')}${course(3, '8,800')}<p class="fine">${t('料理は人数分を大皿で提供します。10名様のご予約は', 'Food is served on shared platters for your group. For 10 guests, ')}<a href="tel:+818087008528">${t('お電話でお問い合わせください', 'please call +81 80 8700 8528')}</a>${t('。', '.')}</p>${ext(links.course, t('コースの詳細・予約', 'Course details & booking'), 'button button-outline', 'course_outbound')}<p class="fine destination-note">TableCheck${t('', ' · Course details in Japanese')}</p></div></section>
<section class="house" id="house" aria-labelledby="house-title"><div class="wrap house-inner"><span class="floor-mark">1F</span><div><p class="eyebrow">BOTTLE SHOP / ${t('準備中', 'IN PREPARATION')}</p><h2 id="house-title">${t('その一杯の続きを、家へ。', 'From a glass to a bottle.')}</h2><p>${t('2Fで出会った味を、1Fで探せる場所へ。<br>ただいま、ボトルショップを準備しています。', 'We’re preparing a bottle shop on 1F.<br>A place to look for your next bottle, inspired by what you discover upstairs.')}</p></div><a href="#experience" class="house-return" aria-label="${t('2Fのバーを見る', 'Discover the 2F bar')}">2F ↑</a></div></section>
<section class="visit section wrap" id="access" aria-labelledby="visit-title"><span id="hours" class="anchor-alias"></span><div class="visit-heading"><p class="eyebrow">COME ON IN</p><h2 id="visit-title">${t('赤坂で、<br>お待ちしています。', 'See you<br>in Akasaka.')}</h2></div><figure class="alley">${photo('07-alley', 960, 960, 720, t('赤坂の路地にあるチルラボへの入口', 'The alley leading to Chill Labo in Akasaka'))}<figcaption>${t('この路地の先へ。バーは2Fです。', 'Look for this alley. The bar is on 2F.')}</figcaption></figure><div class="visit-details"><h3>Chill Labo Akasaka <span>Japanese Sake Bar</span></h3><address>${t('〒107-0052<br>東京都港区赤坂4-3-27 2F', '2F, 4-3-27 Akasaka, Minato-ku<br>Tokyo 107-0052, Japan')}</address><p>${t('赤坂駅・赤坂見附駅から徒歩約5分', 'About a 5-minute walk from Akasaka Station<br>or Akasaka-mitsuke Station')}</p>${ext(links.maps, t('Google Mapsで道順を見る', 'Get directions on Google Maps'), 'text-link', 'maps_outbound')}<dl class="hours"><div><dt>${t('月〜金', 'Mon–Fri')}</dt><dd>17:00–23:00 <small>L.O. 22:00</small></dd></div><div><dt>${t('土', 'Saturday')}</dt><dd>15:00–22:00 <small>L.O. 21:15</small></dd></div><div><dt>${t('日', 'Sunday')}</dt><dd>${t('定休日', 'Closed')}</dd></div></dl><p class="fine">${t('祝日は基本営業。臨時休業・営業時間の変更はInstagram・Google Mapsをご確認ください。', 'All times are Japan time (JST). Generally open on public holidays. Check Instagram or Google Maps for temporary closures and holiday updates.')}</p><a href="tel:+818087008528" class="phone">${t('080-8700-8528', '+81 80 8700 8528')}</a><p class="fine">${t('現金・クレジットカード・PayPay / 店内禁煙（屋外喫煙スペースあり）', 'Cash, credit cards & PayPay / Non-smoking indoors; outdoor smoking area available')}</p></div>
<details class="hotel-routes"><summary>${t('近くのホテルからの道順', 'Staying nearby? Directions from your hotel')}<span class="toggle" aria-hidden="true"></span></summary><div class="hotel-grid">${hotels.map(([ja, name, street]) => { const url = 'https://www.google.com/maps/dir/?' + new URLSearchParams({api:'1', origin:`${name}, ${street} Akasaka, Minato-ku, Tokyo, Japan`, destination:'Chill Labo, 4-3-27 Akasaka, Minato-ku, Tokyo, Japan', travelmode:'walking'}); return ext(url, esc(t(ja, name)), 'hotel-link', 'hotel_directions'); }).join('')}</div></details>
<div class="booking"><div><p class="eyebrow">SAVE A SEAT</p><h3>${t('予約はInstagramのDMで。', 'Reserve by Instagram DM.')}</h3><p>${t('日付・時間・人数をお送りください。<br>お店からの返信で、ご予約を確認します。', 'Send your preferred date, time and party size.<br>Please wait for the restaurant to confirm your reservation.')}</p>${actions()}</div><div class="booking-help"><details><summary>${t('予約メッセージのひな形', 'A message you can copy')}<span class="toggle" aria-hidden="true"></span></summary><div class="details-content"><p id="dm-message">${dm}</p><button type="button" class="copy-button" id="copy-message" hidden>${t('メッセージをコピー', 'Copy message')}</button><p class="copy-status fine" role="status" aria-live="polite"></p></div></details><p class="fine">${t('お席があれば当日のご来店も歓迎。金曜日の3名様以上は予約がおすすめです。16時以降の当日予約・10名様以上は、お電話でお問い合わせください。料理付きコースは2日前までの予約制です。', 'Walk-ins are welcome when seats are available. Booking is recommended for Friday groups of three or more. For same-day reservations after 16:00 JST, or groups of 10 or more, please call. Food courses still require booking at least 2 days ahead.')}</p><p class="fine">${t('遅れる場合はお電話ください。ご予約時刻から20分を過ぎて未到着の場合、キャンセルとなることがあります。お席の指定はご希望に添えない場合があります。', 'Please call if you are running late. Your reservation may be cancelled if you have not arrived within 20 minutes of the booked time. Seating requests may not always be available.')}</p></div></div></section>
<section class="faq section wrap" id="faq" aria-labelledby="faq-title"><div><p class="eyebrow">GOOD TO KNOW</p><h2 id="faq-title">${t('来る前に、<br>少しだけ。', 'Before<br>your visit.')}</h2>${ext(links.maps, t('Google Mapsで店舗・口コミを見る', 'View the bar & guest reviews on Google Maps'), 'text-link', 'maps_outbound')}</div><div class="faq-list">${faqs.map(([q,a], i) => `<details><summary>${q}<span class="toggle" aria-hidden="true"></span></summary><div class="details-content"><p>${a}</p>${i === 5 ? `<a class="text-link" href="#courses">${t('料理付きコースを見る', 'See the food courses')} ↓</a>` : ''}</div></details>`).join('')}</div></section>
<section class="discover section wrap" id="discover" aria-labelledby="discover-title"><a class="label-art" href="${links.sat}" target="_blank" rel="noopener noreferrer" aria-label="${t('SAKE ART TOKYOのトップページへ', 'Visit the SAKE ART TOKYO homepage')}" data-track="sat_outbound">${photo('sat-001-label', 900, 900, 1111, t('SAKE ART TOKYO SAT 001の実際のラベルアート', 'The original label artwork for SAKE ART TOKYO SAT 001'))}</a><div class="discover-copy"><p class="eyebrow">SAKE ART TOKYO</p><h2 id="discover-title">${t('この店、<br>酒もつくっています。', 'We make<br>sake, too.')}</h2><p>${t('飲む場所から、酒蔵と一緒につくる側へ。<br>私たちのクラフト酒と、そのまわりの物語。', 'From serving sake to creating it with breweries.<br>Discover our craft sake, and the stories around it.')}</p>${ext(links.sat, t('つくっている酒を見る', 'Explore the sake we create'), 'text-link', 'sat_outbound')}<p class="fine">${t('SAKE ART TOKYOへ', 'At SAKE ART TOKYO')}</p></div></section>
<section class="field section wrap" id="field" aria-labelledby="field-title"><p class="eyebrow">FROM FIELD TO GLASS</p><h2 id="field-title">${t('一部の酒は、<br>米を植えるところから。', 'Sometimes,<br>we start in the field.')}</h2><div><p>${t('自分たちで田植え・稲刈りをした米を使う、次の一本。<br>SAKE ART TOKYOの3番目のクラフト酒は、そこから始まります。', 'Our third SAKE ART TOKYO craft sake begins with rice we planted and harvested ourselves.')}</p><p class="fine">${t('一本の酒ができるまでの記録は、これから。', 'The story of that bottle is still unfolding.')}</p></div><p class="field-line" aria-label="${t('田んぼ、米、発酵、グラス、ボトル、物語', 'Field, rice, fermentation, glass, bottle, story')}">FIELD <span>→</span> RICE <span>→</span> FERMENTATION <span>→</span> GLASS <span>→</span> BOTTLE <span>→</span> STORY</p></section>
<section class="playground" id="playground" aria-labelledby="play-title"><div class="wrap playground-inner"><div><p class="eyebrow">FERMENTATION PLAYGROUND</p><h2 id="play-title">${t('飲んだ違いを、<br>もう少し知る。', 'A little more<br>behind every sip.')}</h2><p>${t('香りのこと。米のこと。<br>グラスの向こうを、ちょっと探検。', 'Aromas, rice, and what happens in between.<br>Explore a little beyond your glass.')}</p></div><div class="play-links">${ext(links.play + '#aroma', `<span><small>01 / AROMA LAB</small>${t('香りを比べる', 'Compare aromas')}</span>`, 'play-link', 'playground_outbound')}${ext(links.play + '#rice', `<span><small>02 / RICE LINEAGE</small>${t('酒米の家系図を見る', 'Explore the family tree of sake rice')}</span>`, 'play-link', 'rice_lineage_outbound')}<p class="fine">${t('酒米を知る。その先には、本当に米を育て、酒をつくる人たちがいます。', 'Behind the rice you learn about are real people growing it and making sake.')}</p></div></div></section>
<section class="return section wrap" id="return" aria-labelledby="return-title"><p class="eyebrow">FROM SCREEN TO GLASS</p><h2 id="return-title">${t('次の一杯も、ここで。', 'Your next sip starts here.')}</h2>${actions()}<p class="fine">${t('赤坂の日本酒バー / 2F / お一人様も、はじめましても。', 'Japanese sake bar / Akasaka, Tokyo / 2F / Come as you are.')}</p></section>
</main><footer class="site-footer wrap"><div><a class="brand footer-brand" href="#top"><span class="wordmark">CHILL LABO</span><span class="brand-place">AKASAKA</span></a><p class="fine">${t('東京都港区赤坂4-3-27 2F', '2F, 4-3-27 Akasaka, Minato-ku, Tokyo')}<br><a href="tel:+818087008528">${t('080-8700-8528', '+81 80 8700 8528')}</a></p></div><nav aria-label="${t('関連サイト', 'Related sites')}">${ext(links.sat, 'SAKE ART TOKYO')}${ext(links.play, 'FERMENTATION PLAYGROUND')}${ext(links.reserve, 'Instagram')}<a class="language-link" href="${en ? '../' : './en/'}" lang="${en ? 'ja' : 'en'}">${t('English', '日本語')}</a></nav><p class="copyright">© ${new Date().getFullYear()} CHILL LABO AKASAKA</p></footer>
<aside class="sticky-actions" aria-label="${t('予約と地図', 'Booking and directions')}" hidden>${reserve()}${maps(true)}</aside>
</body></html>`;
}
await mkdir(path.join(root, 'en'), { recursive: true });
for (const lang of ['ja', 'en']) await writeFile(path.join(root, lang === 'ja' ? 'index.html' : 'en/index.html'), render(lang).split('\n').map(line => line.trimEnd()).join('\n'));
await writeFile(path.join(root, 'robots.txt'), `User-agent: GPTBot\nDisallow: /\n\nUser-agent: *\nAllow: /\n${indexable ? `Sitemap: ${origin}/sitemap.xml\n` : '# Preview pages carry noindex; crawling is allowed to read that directive.\n'}`);
await writeFile(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${origin}/</loc></url><url><loc>${origin}/en/</loc></url></urlset>\n`);
await writeFile(path.join(root, '404.html'), `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Page not found | Chill Labo</title><link rel="stylesheet" href="${origin}/assets/css/styles.css"></head><body><main class="not-found wrap"><p class="eyebrow">CHILL LABO AKASAKA / 404</p><h1>このページは<br>見つかりませんでした。</h1><p>We couldn’t find this page.</p><div class="actions"><a class="button button-red" href="${origin}/">日本語TOPへ →</a><a class="button button-outline" href="${origin}/en/">English home →</a></div></main></body></html>`);
console.log(`Built JA / EN: ${origin} (${indexable ? 'indexable' : 'noindex preview'})`);
